default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: short_url_dev

test:
  <<: *default
  database: short_url_test

production:
  <<: *default
  database: short_url_prod